version: 3.2
groups:
  backend-reviewer:
    required: -1
    github_reviews:
      enabled: true
    reset_on_push:
      enabled: true
    users:
      - chantisnake
      - EmmaGrace
      - Landaluce
      - Weiqi97
