version: 3.2
groups:
  code-review:
    required: -1
    approve_by_comment:
      approve_regex: approved|Approved|:\+1:
      enabled: false
      reject_regex: ^Rejected
    reset_on_push:
      enabled: true
    users:
    - chantisnake
    - EmmaGrace
    - Landaluce
    - Weiqi97
