version: 2           # specify pull approve version
groups:
  backend-reviewer:  # reviewer for backend code
    required: -1     # require all reviewer to pass
    github_reviews:  # use github pull request review as indicator for approve
      enabled: true
    reset_on_push:   # every time there is a new push the approves will be reseted
      enabled: true
    users:
      - chantisnake
      - EmmaGrace
      - Landaluce
      - Weiqi97
