language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
    - "pip install -r ./requirements.txt"
    - "pip install -r ./dev_requirements.txt"
# command to run tests
script:
    - "flake8 --count ."
