# Set up matrix for multiple languages check.
matrix:
  include:
    # Check for python 3.6.
    - language: python
      python: "3.7"
      install:
        # Use newest pip and install check tools.
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r dev_requirements.txt
      script:
        # Check styles.
        # test for python static analysis
        # including code style, doc style, and basic code analysis
        # ignore F841 because it includes backhoe variable: "_"
        # ignore E123 because https://github.com/PyCQA/pycodestyle/issues/103
        - flake8 --ignore F841,E123 --count .
        # unit testing
        - pytest --cov=./lexos
        - codecov
        # doc style, at the moment only test files under models and receivers.
        - pydocstyle lexos/models/
        - pydocstyle lexos/receivers/

    # Check for node_js 10.x.
    - language: node_js
      node_js: "10"
      # Install dependencies.
      install:
        - cd ./lexos/static
        - npm install
      script:
        # Following line is commented out, frontend refactor is not completed
        # - ./node_modules/.bin/eslint ./js/script_*.js
        - ./node_modules/.bin/eslint ./js/scripts_statistics.js
        - ./node_modules/.bin/eslint ./js/scripts_similarity.js
        - ./node_modules/.bin/eslint ./js/scripts_dendrogram.js
        - ./node_modules/.bin/eslint ./js/scripts_rwanalysis.js
        - ./node_modules/.bin/eslint ./js/scripts_upload.js
        - ./node_modules/.bin/eslint ./js/scripts_manage.js
        - ./node_modules/.bin/eslint ./js/scripts_kmeans.js
        - ./node_modules/.bin/eslint ./js/scripts_scrub.js
        - ./node_modules/.bin/eslint ./js/scripts_cut.js
        - ./node_modules/.bin/eslint ./js/scripts_bct.js
